@echo off
echo Clearing Next.js cache and rebuilding...

echo Step 1: Stopping servers...
taskkill /F /IM node.exe 2>nul

echo Step 2: Removing .next folder...
if exist .next rmdir /s /q .next

echo Step 3: Removing out folder...
if exist out rmdir /s /q out

echo Step 4: Clearing npm cache...
npm cache clean --force

echo Step 5: Reinstalling dependencies...
npm install

echo Step 6: Building project...
npm run build

echo Step 7: Starting development server...
npm run dev

echo Done! Check if the webpack error is fixed.
pause
